---
- hosts: all

  vars:
    packages:
      - unzip
      - wget
      - vim
      - curl
    docker_version: 1.12.3
    docker_users:
      - vagrant
    nomad_version: 0.4.1

  tasks:
    - name: update system packages
      become: True
      yum:
        name: "*"
        state: latest
    - name: install packages
      become: True
      yum:
        name: "{{ item }}"
        state: latest
      with_items: "{{ packages }}"

    - name: add docker repository
      become: True
      copy:
        src: resources/docker.repo
        dest: /etc/yum.repos.d/docker.repo
        mode: 0644
    
    - name: install docker engine
      become: True
      yum:
        name: docker-engine-{{ docker_version }}
        state: present
    
    - name: enable docker service
      become: True
      systemd:
        name: docker
        state: started
        enabled: True

    - name: create docker group
      become: True
      group:
        name: docker

    - name: add users in docker group
      become: True
      user:
        name: "{{ item }}"
        append: True
        groups: docker
      with_items: "{{ docker_users }}"

    - name: download nomad
      get_url:
        url: "https://releases.hashicorp.com/nomad/{{ nomad_version }}/nomad_{{ nomad_version }}_linux_amd64.zip"
        dest: "/tmp/nomad_{{ nomad_version }}_linux_amd64.zip"

    - name: install nomad
      become: True
      unarchive:
        src: "/tmp/nomad_{{ nomad_version }}_linux_amd64.zip"
        dest: /usr/local/bin/
        remote_src: True

