---
- name: update system packages
  become: true
  yum:
    name: "*"
    state: latest
- name: install packages
  become: true
  yum:
    name: "{{ item }}"
    state: latest
  with_items: "{{ packages }}"
