---
- hosts: all
  vars:
    packages:
      - unzip
      - wget
      - vim
      - curl
  pre_tasks:
    - include: base.yml
  roles:
    - role: docker
    - role: nomad

- hosts: masters
  roles:
    - consul